name: Preflight results from IBM Power  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build
  Preflight_results:      
      strategy:
          matrix:        
            architecture: [ s390x, ppc64le ]
          fail-fast: false
          max-parallel: 2
      runs-on: ${{ matrix.architecture }}
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: check the ${{ matrix.architecture }} version
        run: |
          sudo lscpu

      - name: Do the cleanup
        run: |
          rm -rf preflight-linux-.*
          rm -rf /usr/local/bin/preflight

      - name: Install preflight 
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          sudo wget https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.7.0-alpha1/preflight-linux-${{ matrix.architecture }}
          # sudo curl -s https://api.github.com/repos/redhat-openshift-ecosystem/openshift-preflight/releases/latest|grep browser_download_url |grep ppc64le|cut -d : -f 2,3|tr -d \"|xargs curl -LO
          sudo chmod u+x preflight-linux-${{ matrix.architecture }}
          sudo mv preflight-linux-${{ matrix.architecture }} /usr/local/bin/preflight
          sudo chmod +x /usr/local/bin/preflight
          preflight --version
          
      - name: Check container image
        run: |
          export PFLT_LOGLEVEL=trace
          export PFLT_JUNIT=true
          preflight check container quay.io/raja0940/rhel-ubi9:latest
          
      - name: Check junit xml results
        run: |
          cat artifacts/${{ matrix.architecture }}/results-junit.xml
          ls artifacts/${{ matrix.architecture }}/
      
      - name: Check Preflight logs
        run: |
          cat preflight.log
      - name: Check results output
        run: |
          cat artifacts/${{ matrix.architecture }}/results.json
